name = "ExactWrightFisher"
uuid = "8c1589a6-e1d0-11e8-3509-29fca4fccf6a"
authors = ["konkam <guillaume.konkamking.work@gmail.com>"]
version = "0.1.11"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Distributions = "0.23, 0.24, 0.25"
Nemo = "0.39, 0.40, 0.41, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49"
ProgressMeter = "1"
SpecialFunctions = "0.9, 0.10, 1.0, 1.3, 1.6, 2"
StatsFuns = "0.9, 0.10, 1"
julia = "1"
